"ENV_NAME": "overcooked"  # ToyCoop or overcooked #checked
"NUM_ENVS": 512
"NUM_STEPS": 100
"TOTAL_TIMESTEPS": 3e9 #checked #for overcooked : 3e9
"SEED": 0
"ENV_KWARGS": 
  "random_reset" : True #checked # relevant for which env to train/test on. If true, it is CEC, otherwise single task
  "max_steps": 100
  "check_held_out": True  # if false, we don't check if the reset env is held out
  # overcooked specific kwargs
  "shuffle_inv_and_pot": False # if true, we shuffle pot status and inventory
  "layout": "cramped_room_9"  # relevant for overcooked, all CEC compatible envs have the "_9" in the name at the end
  "random_reset_fn": "reset_all"  # reset_all or reset_counter_circuit  
"SAVE_INTERVAL": 1  # save env_states every N updates (io_callback) # uncomment to save only these; omit or null = save all